language: node_js
node_js:
  - "14"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href https://caseyhoover.github.io/travis-demo/