language: node_js
node_js:
  - "14"
dist: trusty
sudo: required
before_script:
  - cd travis-demo
  - npm install -g @angular/cli
  - npm install --save-dev @angular-devkit/build-angular
script:
- ng lint
- ng build --prod --base-href https://caseyhoover.github.io/travis-demo/