name: Angular Workflow
on: pull_request
jobs:
  docker-test:
      runs-on: ubuntu-latest
      name: Analyze Dockerized Angular Project 
      defaults:
        run:
          working-directory: ./travis-demo
      steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Docker Image
        run: docker build -f Dockerfile-test --tag job .

      - name: Start Docker Container
        run: docker run -t -d --name="test-container" job
        
      - name: Lint Angular Project
        run: docker exec test-container ng lint

      - name: Run Angular Unit Tests
        run: docker exec test-container ng test --watch=false

      - name: Copy Coverage Report to Host
        run: |
          docker cp test-container:/app/coverage/travis-demo/lcov.info ..
          pwd
          cat ../lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./lcov.info
          verbose: true

      # - name: Push Build to Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "dist/angular-githubaction/*"
      #     token: ${{ secrets.CICD }}
