name: Merge Main Workflow

on:
  push:
    branches: [main]
    # Sequence of patterns matched against refs/tags

jobs:
  build-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v1

      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN }}